//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HrDbContext : DbContext
    {
        public HrDbContext()
            : base("name=HrDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Table_BonusInfo> Table_BonusInfo { get; set; }
        public virtual DbSet<Table_ChildrenInfo> Table_ChildrenInfo { get; set; }
        public virtual DbSet<Table_CostCenter> Table_CostCenter { get; set; }
        public virtual DbSet<Table_Department> Table_Department { get; set; }
        public virtual DbSet<Table_EducationInfo> Table_EducationInfo { get; set; }
        public virtual DbSet<Table_Employee> Table_Employee { get; set; }
        public virtual DbSet<Table_FamilyMembersInfo> Table_FamilyMembersInfo { get; set; }
        public virtual DbSet<Table_Headcount> Table_Headcount { get; set; }
        public virtual DbSet<Table_InternalLevel> Table_InternalLevel { get; set; }
        public virtual DbSet<Table_Offer> Table_Offer { get; set; }
        public virtual DbSet<Table_OfferCycle> Table_OfferCycle { get; set; }
        public virtual DbSet<Table_PersonelInfo> Table_PersonelInfo { get; set; }
        public virtual DbSet<Table_ReportingInfo> Table_ReportingInfo { get; set; }
        public virtual DbSet<Table_Resignation> Table_Resignation { get; set; }
        public virtual DbSet<Table_Role> Table_Role { get; set; }
        public virtual DbSet<Table_SalaryInfo> Table_SalaryInfo { get; set; }
        public virtual DbSet<Table_Survey> Table_Survey { get; set; }
        public virtual DbSet<Table_WorkExperienceInfo> Table_WorkExperienceInfo { get; set; }
        public virtual DbSet<Table_EmailAccount> Table_EmailAccount { get; set; }
        public virtual DbSet<Table_TypeRoleAccess> Table_TypeRoleAccess { get; set; }
        public virtual DbSet<Table_UserRole> Table_UserRole { get; set; }
    
        public virtual int Proc_GetEmailAccountPwd(ObjectParameter returnVal, string emailAddress)
        {
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GetEmailAccountPwd", returnVal, emailAddressParameter);
        }
    
        public virtual int Proc_GetRoleName(ObjectParameter returnVal, string domainLogin, string roleName)
        {
            var domainLoginParameter = domainLogin != null ?
                new ObjectParameter("DomainLogin", domainLogin) :
                new ObjectParameter("DomainLogin", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GetRoleName", returnVal, domainLoginParameter, roleNameParameter);
        }
    
        public virtual int Proc_GetUserName(ObjectParameter returnVal, string domainLogin)
        {
            var domainLoginParameter = domainLogin != null ?
                new ObjectParameter("DomainLogin", domainLogin) :
                new ObjectParameter("DomainLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_GetUserName", returnVal, domainLoginParameter);
        }
    
        public virtual int Proc_InsertAddressBook(Nullable<int> offerID, Nullable<int> sID)
        {
            var offerIDParameter = offerID.HasValue ?
                new ObjectParameter("OfferID", offerID) :
                new ObjectParameter("OfferID", typeof(int));
    
            var sIDParameter = sID.HasValue ?
                new ObjectParameter("SID", sID) :
                new ObjectParameter("SID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_InsertAddressBook", offerIDParameter, sIDParameter);
        }
    
        public virtual int Proc_InsertNewAccount(ObjectParameter returnVal, Nullable<int> offerID, string domainLogin, Nullable<System.DateTime> contractStartDate)
        {
            var offerIDParameter = offerID.HasValue ?
                new ObjectParameter("OfferID", offerID) :
                new ObjectParameter("OfferID", typeof(int));
    
            var domainLoginParameter = domainLogin != null ?
                new ObjectParameter("DomainLogin", domainLogin) :
                new ObjectParameter("DomainLogin", typeof(string));
    
            var contractStartDateParameter = contractStartDate.HasValue ?
                new ObjectParameter("ContractStartDate", contractStartDate) :
                new ObjectParameter("ContractStartDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_InsertNewAccount", returnVal, offerIDParameter, domainLoginParameter, contractStartDateParameter);
        }
    
        public virtual int Proc_InsertNewEmployee(ObjectParameter returnVal, Nullable<int> offerID, string user)
        {
            var offerIDParameter = offerID.HasValue ?
                new ObjectParameter("OfferID", offerID) :
                new ObjectParameter("OfferID", typeof(int));
    
            var userParameter = user != null ?
                new ObjectParameter("User", user) :
                new ObjectParameter("User", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_InsertNewEmployee", returnVal, offerIDParameter, userParameter);
        }
    }
}
