//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_InternalLevel
    {
        public int InternalLevel_ID { get; set; }
        public string InternalLevel_Name { get; set; }
        public Nullable<bool> InternalLevel_Active { get; set; }
        public Nullable<System.DateTime> InternalLevel_CreatedAt { get; set; }
        public string InternalLevel_CreatedBy { get; set; }
        public Nullable<System.DateTime> InternalLevel_ModifiedAt { get; set; }
        public string InternalLevel_ModifiedBy { get; set; }
    }
}
