//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Resignation
    {
        public int Resignation_ID { get; set; }
        public int Resignation_EmpID { get; set; }
        public string Resignation_Status { get; set; }
        public Nullable<System.DateTime> Resignation_ResignDate { get; set; }
        public Nullable<System.DateTime> Resignation_LastWorkingDate { get; set; }
        public Nullable<System.DateTime> Resignation_DomainEndDate { get; set; }
        public Nullable<System.DateTime> Resignation_CreatedAt { get; set; }
        public string Resignation_CreatedBy { get; set; }
        public Nullable<System.DateTime> Resignation_ModifiedAt { get; set; }
        public string Resignation_ModifiedBy { get; set; }
    }
}
