//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Headcount
    {
        public int Headcount_ID { get; set; }
        public int Headcount_Code { get; set; }
        public string Headcount_Position { get; set; }
        public Nullable<int> Headcount_Number { get; set; }
        public string Headcount_CostCenter { get; set; }
        public string Headcount_Department { get; set; }
        public string Headcount_InternalLevel { get; set; }
        public Nullable<System.DateTime> Headcount_CreatedAt { get; set; }
        public string Headcount_CreatedBy { get; set; }
        public Nullable<System.DateTime> Headcount_ModifiedAt { get; set; }
        public string Headcount_ModifiedBy { get; set; }
        public string Headcount_Status { get; set; }
    }
}
