//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Survey
    {
        public int Survey_ID { get; set; }
        public Nullable<int> Survey_SourceID { get; set; }
        public string Survey_SourceType { get; set; }
        public string Survey_Content { get; set; }
        public Nullable<System.DateTime> Survey_CreatedAt { get; set; }
        public string Survey_CreatedBy { get; set; }
        public Nullable<System.DateTime> Survey_ModifiedAt { get; set; }
        public string Survey_ModifiedBy { get; set; }
    }
}
