//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TypeRoleAccess
    {
        public int TypeRoleAccess_ID { get; set; }
        public string TypeRoleAccess_TypeFullName { get; set; }
        public string TypeRoleAccess_Role { get; set; }
        public string TypeRoleAccess_Permission { get; set; }
        public bool TypeRoleAccess_Active { get; set; }
        public string TypeRoleAccess_CreatedBy { get; set; }
        public Nullable<System.DateTime> TypeRoleAccess_CreatedAt { get; set; }
        public string TypeRoleAccess_ModifiedBy { get; set; }
        public Nullable<System.DateTime> TypeRoleAccess_ModifiedAt { get; set; }
    }
}
