//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Offer
    {
        public int Offer_ID { get; set; }
        public int Offer_HCID { get; set; }
        public string Offer_Status { get; set; }
        public int Offer_PersonelInfoID { get; set; }
        public Nullable<int> Offer_SalaryInfoID { get; set; }
        public Nullable<int> Offer_ReportingInfoID { get; set; }
        public string Offer_RecruitType { get; set; }
        public string Offer_Position { get; set; }
        public string Offer_Location { get; set; }
        public Nullable<System.DateTime> Offer_OnboardingDate { get; set; }
        public string Offer_RecruitChannel { get; set; }
        public Nullable<int> Offer_ProbationDuration { get; set; }
        public string Offer_Notes { get; set; }
        public string Offer_SignedFile { get; set; }
        public Nullable<System.DateTime> Offer_CreatedAt { get; set; }
        public string Offer_CreatedBy { get; set; }
        public Nullable<System.DateTime> Offer_ModifiedAt { get; set; }
        public string Offer_ModifiedBy { get; set; }
        public Nullable<bool> Offer_EmailITCompleted { get; set; }
        public Nullable<bool> Offer_SyncDomainCompleted { get; set; }
        public Nullable<bool> Offer_WelcomeCandidateCompleted { get; set; }
        public Nullable<bool> Offer_WelcomeToMgrCompleted { get; set; }
    }
}
