//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_AddressBook
    {
        public int SID { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string HomeTel { get; set; }
        public string Mobile { get; set; }
        public string Ext { get; set; }
        public string OfficeEmail { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string PicLocation { get; set; }
        public string Cube { get; set; }
        public string EmergencyContactPerson { get; set; }
        public string EmergencyContactPhone { get; set; }
        public string BadgeNumber { get; set; }
    }
}
