//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_EmailAccount
    {
        public int EmailAccount_ID { get; set; }
        public string EmailAccount_Address { get; set; }
        public byte[] EmailAccount_Pwd { get; set; }
    }
}
