//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_EmpType
    {
        public int EmpType_ID { get; set; }
        public string EmpType_Name { get; set; }
        public string EmpType_Description { get; set; }
        public string EmpType_ModifiedBy { get; set; }
        public Nullable<System.DateTime> EmpType_ModifiedAt { get; set; }
    }
}
