//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ChildrenInfo
    {
        public int ChildrenInfo_ID { get; set; }
        public int ChildrenInfo_PersonelInfoID { get; set; }
        public string ChildrenInfo_FullName { get; set; }
        public string ChildrenInfo_Gender { get; set; }
        public string ChildrenInfo_BirthDate { get; set; }
        public Nullable<System.DateTime> ChildrenInfo_CreatedAt { get; set; }
        public string ChildrenInfo_CreatedBy { get; set; }
        public Nullable<System.DateTime> ChildrenInfo_ModifiedAt { get; set; }
        public string ChildrenInfo_ModifiedBy { get; set; }
    }
}
