//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_OfferCycle
    {
        public int OfferCycle_ID { get; set; }
        public string OfferCycle_ProcessName { get; set; }
        public string OfferCycle_ProcessDescription { get; set; }
        public string OfferCycle_StartStatus { get; set; }
        public string OfferCycle_EndStatus { get; set; }
        public Nullable<System.DateTime> OfferCycle_CreatedAt { get; set; }
        public string OfferCycle_CreatedBy { get; set; }
        public Nullable<System.DateTime> OfferCycle_ModifiedAt { get; set; }
        public string OfferCycle_ModifiedBy { get; set; }
    }
}
