//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_EducationInfo
    {
        public int EducationInfo_ID { get; set; }
        public int EducationInfo_PersonelInfoID { get; set; }
        public string EducationInfo_StartDate { get; set; }
        public string EducationInfo_EndDate { get; set; }
        public string EducationInfo_School { get; set; }
        public string EducationInfo_Major { get; set; }
        public string EducationInfo_Degree { get; set; }
        public Nullable<System.DateTime> EducationInfo_CreatedAt { get; set; }
        public string EducationInfo_CreatedBy { get; set; }
        public Nullable<System.DateTime> EducationInfo_ModifiedAt { get; set; }
    }
}
