//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_BonusInfo
    {
        public int BonusInfo_ID { get; set; }
        public int BonusInfo_SalaryInfoID { get; set; }
        public string BonusInfo_Type { get; set; }
        public decimal BonusInfo_Amount { get; set; }
        public string BonusInfo_CreatedBy { get; set; }
        public Nullable<System.DateTime> BonusInfo_CreatedAt { get; set; }
        public string BonusInfo_ModifiedBy { get; set; }
        public Nullable<System.DateTime> BonusInfo_ModifiedAt { get; set; }
    }
}
