//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_PersonelInfo
    {
        public int PersonelInfo_ID { get; set; }
        public string PersonelInfo_RomanFName { get; set; }
        public string PersonelInfo_RomanLName { get; set; }
        public string PersonelInfo_FName { get; set; }
        public string PersonelInfo_LName { get; set; }
        public string PersonelInfo_Mobile { get; set; }
        public string PersonelInfo_Email { get; set; }
        public string PersonelInfo_Phone { get; set; }
        public string PersonelInfo_Gender { get; set; }
        public string PersonelInfo_MartialStatus { get; set; }
        public Nullable<System.DateTime> PersonelInfo_BirthDate { get; set; }
        public string PersonelInfo_IdentityID { get; set; }
        public string PersonelInfo_Nationality { get; set; }
        public string PersonelInfo_Hukou { get; set; }
        public string PersonelInfo_HukouType { get; set; }
        public string PersonelInfo_FileLocation { get; set; }
        public string PersonelInfo_HomeAddress { get; set; }
        public string PersonelInfo_PostCode { get; set; }
        public string PersonelInfo_EmergencyContact { get; set; }
        public string PersonelInfo_EmergencyContactPhone { get; set; }
        public Nullable<System.DateTime> PersonelInfo_CreatedAt { get; set; }
        public string PersonelInfo_CreatedBy { get; set; }
        public Nullable<System.DateTime> PersonelInfo_ModifiedAt { get; set; }
        public string PersonelInfo_ModifiedBy { get; set; }
    }
}
