//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NI.Apps.Hr.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EmpOverView
    {
        public string Name { get; set; }
        public string English_First_Name { get; set; }
        public string English_Last_Name { get; set; }
        public string Home_Address { get; set; }
        public string Emergency_Contact_Person { get; set; }
        public string Emergency_Contact_Phone { get; set; }
        public string Badge_Number { get; set; }
        public string Home_Phone { get; set; }
        public string Mobile { get; set; }
        public string Office_Phone_Ext_ { get; set; }
        public string Cube { get; set; }
        public string Office_Email { get; set; }
    }
}
